#!/bin/bash

rm data.db
FLASK_DEBUG=1 FLASK_APP=/Users/pabs/git/invoices/invoices/ flask initdb
FLASK_DEBUG=1 FLASK_APP=/Users/pabs/git/invoices/invoices/ flask scrape
FLASK_DEBUG=1 FLASK_APP=/Users/pabs/git/invoices/invoices/ flask run
